# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 16:26
from __future__ import unicode_literals

import closeness.users.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', closeness.users.managers.UserManager()),
            ],
        ),
    ]
