# Docker-compose file to launch the database used during the development.
version: '2'

volumes:
  db-data:
    driver: local

services:

  db:
    image: postgres:9
    container_name: closeness-db
    volumes:
      - db-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: potato
      POSTGRES_DB: closeness
