FROM postgres:9.6
MAINTAINER Marcos Gabarda <hey@marcosgabarda.com>

RUN apt-get update && apt-get install -y --no-install-recommends \
    postgresql-9.6-postgis-2.3 \
    postgresql-9.6-postgis-2.3-scripts
