# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 16:35
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('shape', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
